### ISSUE TITLE
Can't pull 7-zip

### ISSUE THREAD

**Issue by delipastrami** [github/evergreen#138]
### Describe the bug

Get-EvergreenApp does not return any results for 7zip. It seems that "Resolve-SystemNetWebRequest" cannot resolve sourceforge address properly.

### To Reproduce

get-evergreenapp -name "7zip" -verbose

### Expected behavior

7zip query returns expected values such as URI, version, etc.

### Screenshots

<img width="1904" alt="Screenshot 2024-05-21 at 3 45 28 PM" src="https://github.com/github/evergreen/assets/47377323/f38fad28-546d-496a-82ff-9433f64abca7">

### Additional context

The get endpoint cmd returns additional URIs for 7zip. Is is possible to ignore or specify certain URIs?

`Get-EvergreenEndpoint -Name "7zip"`

```
Application Endpoints                                                                                  Ports

----------- ---------                                                                                  -----

7zip        {[nchc.dl.sourceforge.net](http://nchc.dl.sourceforge.net/), [sourceforge.net](http://sourceforge.net/), www.7-zip.org, [cytranet-dal.dl.sourceforge.net](http://cytranet-dal.dl.sourceforge.net/)} {443}
```

**Comment by jmeridth** [comment]
@delipastrami did you mean to post this to https://github.com/aaronparker/evergreen instead?

**Comment by delipastrami** [comment]
apologies - yes, that is correct.
