### ISSUE TITLE
Add option to create issue if dependabot security updates did not turn on.

### ISSUE THREAD

**Issue by zkoppert** [github/evergreen#18]
Currently when the action runs, if it determines that security updates aren't enabled, it tries to enable them, but if permissions are limited, then it fails, prints to the actions log, and continues. I think it would be an improvement to  also open an issue in the target repo to ask the repo maintainers to turn on Dependabot security updates.

**Comment by martincostello** [comment]
If implemented this should be opt-in, as in GitHub Enterprise environments the instance not have an appropriate license for it to be possible to configure at all.

**Comment by Abdallah-Afifi** [comment]
Is this still open? 
I can see an implementation for it in the evergreen.py file.

**Comment by zkoppert** [comment]
You are correct, this has been resolved.
