### ISSUE TITLE
Bad output when existing dependabot file does not end with a newline

### ISSUE THREAD

**Issue by Mearman** [github/evergreen#231]
### Describe the bug

When there is an existing dependabot file that does not have a new line after the last entry, the new entries start on the existing last line and produce an invalid file

### To Reproduce

-

### Expected behavior

-

**Comment by zkoppert** [comment]
I just [wrote a test to reproduce this scenario](https://github.com/github/evergreen/pull/232). I'll look at fixing this bug which should result in getting the test to pass.

**Comment by zkoppert** [comment]
A fix is ready for review: https://github.com/github/evergreen/pull/232

**Comment by Mearman** [comment]
Wow. Lightning fast turnaround. Thank you.
