### ISSUE TITLE
Document which permissions are required to automatically enable security updates

### ISSUE THREAD

**Issue by pnacht** [github/evergreen#25]
#14 allows Evergreen to automatically enable security updates on all repos in an org. However, there's no documentation of which permissions are required for this to work.

The docs in the REST API only state that "The authenticated user must have admin access to the repository", but I don't know how that translates to fine-grained tokens. I assume "Administration", but the REST API uses "admin access" broadly, so clarity in the docs is useful.

**Comment by Abdallah-Afifi** [comment]
Is this still open? I could not locate the line you mentioned in the docs.

**Comment by pnacht** [comment]
Ah sorry, I forgot to link to the relevant docs.

It's the [REST API to enable automated security fixes](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#enable-automated-security-fixes):

> Enables automated security fixes for a repository. The authenticated user must have admin access to the repository.

Indeed, in order to even find those docs, I had to first take a look at the code in #14 and identify which API endpoint it used. I believe that information should be in the Action's README, which already includes some information regarding the necessary permissions:

https://github.com/github/evergreen/blob/13006b92ace9f5a838300bbd2dba57e162934e88/README.md?plain=1#L26

It currently states that the Action only needs "permissions to read the repository/organization and write issues or pull requests". However, I assume*  it actually requires the following fine-grained permissions (adding  "Administration: read-write").

![Screenshot 2024-02-14 at 11 42 20](https://github.com/github/evergreen/assets/15221358/b297ceae-9b72-4ed1-b7a0-a36786f51f11)

I believe this is important because the ability to guarantee all of an org's repos have automated remediation is one of the best features in Evergreen. However, (if I'm correct that it requires "Administration: read-write") it does come with the massive drawback of sharing a long-lived token that can literally destroy all of the org's repositories to an Action I don't control. This is something that should be made clear and explicit to Evergreen's users.

----

\* I admit I haven't actually tested this yet, which is why I haven't sent it as a PR

**Comment by gbrindisi** [comment]
> I believe this is important because the ability to guarantee all of an org's repos have automated remediation is one of the best features in Evergreen. However, (if I'm correct that it requires "Administration: read-write") it does come with the massive drawback of sharing a long-lived token that can literally destroy all of the org's repositories to an Action I don't control. 

It does indeed require `administration:write`: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#enable-automated-security-fixes

I agree with you, until there are permissions to match the Security Manager role it's not great to give admin write to a github action. I'd rather configure the security updates manually on the organization, and leave evergreen to roll out dependabot config for version updates.

It would be useful to make the call to enable security updates optional.
