### ISSUE TITLE
Plans to use a GitHub App Key rather than PAT?

### ISSUE THREAD

**Issue by edwardsph** [github/evergreen#33]
A fine-grained GitHub App key would seem much better suited to this action than a PAT which would need renewing regularly. Are there any plans for this or am I missing something?

**Comment by chrheg** [comment]
I belive this action and most of the calls should work out of the box with the `ghs_` token that you get from a GitHub app. You could use actions like this to generate it: https://github.com/navikt/github-app-token-generator and then just input that as the PAT value. 
But this needs testing and verification of course.

Could also be built in as well pretty easily to the auth part as well.

**Comment by edwardsph** [comment]
Thanks - that extra action sounds useful so I might try that initially. Having implemented an application to get GitHub App tokens, I agree it would be a simple addition to the auth part. Perhaps that could go on the roadmap?

**Comment by chrheg** [comment]
Another benefit of this is that the API Rate Limit is also increased from 5,000 to 15,000 for Enterprise Customers.

**Comment by jmeridth** [comment]
@edwardsph this was solved with #79 (merged)
