### ISSUE TITLE
Duplicate PRs filed against same eligible repository

### ISSUE THREAD

**Issue by lelia** [github/evergreen#57]
If you run `evergreen` multiple times against the same eligible repository, duplicate PRs may be generated, as it is [checking for](https://github.com/github/evergreen/blob/48e30102cc0dcea11473636c606c6d75a4c608d2/evergreen.py#L56-L63) the presence / lack of a `dependabot.y*ml` file each time:

<img width="423" alt="Screenshot 2024-02-21 at 7 19 38 PM" src="https://github.com/github/evergreen/assets/2418071/8f1bee54-35ac-4e7d-98d0-d0d64d39565f">

A possible solution could be to do something similar to what the Scorecard Action installer does, which simply [checks if a matching branch already exists](https://github.com/ossf/scorecard-action/blob/main/install/install.go#L171-L183), and skips the PR creation step whenever there's a match.

However, this may require reworking the [branch commit logic](https://github.com/github/evergreen/blob/main/evergreen.py#L215-L225), which currently uses the pattern of `"dependabot-[uuid-from-commit-SHA]"` to create PR branches. We don't necessarily have to match the branch name 100%, but I'm not sure if partially matching on `dependabot-*` could introduce other issues - or maybe not, if Dependabot does not, in fact, exist on said repository.

**Comment by gbrindisi** [comment]
weird that shouldn't happen there is a simple check for duplicate pr/issues based on the title: https://github.com/github/evergreen/blob/main/evergreen.py#L188-L209

**Comment by lelia** [comment]
> weird that shouldn't happen there is a simple check for duplicate pr/issues based on the title: https://github.com/github/evergreen/blob/main/evergreen.py#L188-L209

Hmm, I wonder if it has something to do with the actual PR title I'm passing in, then? Could `.startswith()` be getting tripped up by the `.` character in `.github: Add Dependabot configuration` ?

**Comment by gbrindisi** [comment]
I found the bug in https://github.com/github/evergreen/blob/48e30102cc0dcea11473636c606c6d75a4c608d2/evergreen.py#L193

Instead of comparing the title with the title, it is comparing the title with `head.ref`.
